### ISSUE TITLE
Montar um trabalho final 

### ISSUE THREAD

**Issue by azeloc** [curso-r/main-pacotes#2]
É importante que no final do curso as pessoas treinem a criação de um pacote. Pensamos no seguinte:

Criar um pacote do 0 que implemente os 5 verbos do dplyr usando R-base. As pessoas alunas podem partir de um script de exemplo que tenha as 5 funções implementadas ou montar do 0.

Pré-requisitos da entrega:

Tem que ter pelo menos 1 teste pra cada função
O pacote não pode ter erros no devtools::check() [AVALIAR]

**Comment by clente** [comment]
Em discussão com a Bea já. Vamos adicionar no curso em breve.
